/* ==================================================================== *
 *  Service tickets — endorsements and claims, the RM's book
 * ==================================================================== */
var CPHASES=['Intimated','Surveyor appointed','Under assessment','Decision','Settled'];
function svcNeed(t){ return !!(t.query&&t.query.open) || (t.wait==='Client'&&(t.out||[]).some(function(d){return !d.got;})); }
function svcClosed(t){ return t.stage==='Settled'||t.stage==='Completed'||t.stage==='Withdrawn'||t.stage==='Repudiated'; }
function svcPhaseIdx(t){ if(t.k==='end') return t.stage==='Withdrawn'?-1:(t.phase||0); var m={'Intimated':0,'Surveyor appointed':1,'Under assessment':2,'Repudiation contested with the insurer':2,'Approved':3,'Repudiated':3,'Settled':4,'Withdrawn':-1}; return m[t.stage]===undefined?0:m[t.stage]; }
function svcClientLabel(t){ return t.client||t.stage; }
function svcById(id){ return by(S.data.svc,id); }
function polOf(t){ var a=acctOf(t.acct); return a?a.pols.filter(function(p){return p.id===t.pol;})[0]:null; }
/* [stated 24 Sep · TBD-52] whoever owns the account works its service tickets, whatever their role */
function svcCanAct(t){ var a=acctOf(t.acct); return !!a && a.own===S.user && !svcClosed(t); }
function svcMine(t,u){ var a=acctOf(t.acct); if(!a) return false; if(u.role==='rm') return a.own===u.id; if(u.role==='rmhead') return rmTeam(u.id).some(function(x){return x.id===a.own;}); return true; }

SCREENS.svc=function(){ return SCREENS.tickets(); };

/* ---------- raise a ticket: a page, not a modal — the forms are long ---------- */
HANDLERS.push(function(t){ var x=t.closest('[data-go="svcnew"]'); if(!x) return false; if(x.disabled) return true;
  ['sn_k','sn_acct','sn_pol','sn_type','sn_cause','sn_dol','sn_est','sn_desc','sn_docs','sn_chan'].forEach(function(k){ delete S.ui[k]; }); Object.keys(S.ui).forEach(function(k){ if(k.indexOf('sn_f')===0) delete S.ui[k]; });
  if(x.dataset.kind) S.ui.sn_k=x.dataset.kind; if(x.dataset.acct) S.ui.sn_acct=x.dataset.acct; if(x.dataset.pol) S.ui.sn_pol=x.dataset.pol; go('svcnew'); return true; });
function snErr(){
  var e={}, k=S.ui.sn_k, a=by(S.data.accounts,S.ui.sn_acct||''), p=a?a.pols.filter(function(x){return x.id===S.ui.sn_pol;})[0]:null;
  if(!k) e.k='Pick endorsement or claim.'; if(!a) e.acct='Pick the account.'; if(a&&!p) e.pol='Pick the policy.';
  if(p&&(p.expired||p.exp<S.now)){ if(k==='end') e.pol='This policy expired on '+fmtD(p.exp)+'. An endorsement cannot be raised on an expired policy — a renewal is the route.'; }
  if(k==='end'){ var ty=ENDO[S.ui.sn_type]; if(!ty) e.type='Pick what needs to change.'; else ty.f.forEach(function(f,i){ var v=(S.ui['sn_f'+i]||'').trim(); if(f[2]&&!v) e['f'+i]='Required.'; else if(v&&f[1]==='cur'&&!/\d/.test(v)) e['f'+i]='Give an amount, e.g. ₹24 Cr.'; else if(v&&f[1]==='pin'&&!/^\d{6}$/.test(v)) e['f'+i]='A six-digit PIN code.'; }); }
  if(k==='clm'){ if(!S.ui.sn_cause) e.cause='Pick the cause of loss.'; var d=S.ui.sn_dol; if(!d) e.dol='When did it happen?'; else { var dt=new Date(d+'T12:00:00').getTime(); if(dt>S.now) e.dol='A loss cannot be in the future.'; else if(p&&dt>p.exp) e.dol='After the policy expired on '+fmtD(p.exp)+'. The loss is not covered under this policy.'; } var est=(S.ui.sn_est||'').trim(); if(!est) e.est='An estimate, even rough.'; else if(!/\d/.test(est)) e.est='Give an amount.'; if(!(S.ui.sn_desc||'').trim()) e.desc='What happened, in a line or two.'; }
  var docs=(S.ui.sn_docs||'').split('|').filter(Boolean), req=snDocs().filter(function(d){return d[1];}); req.forEach(function(d){ if(docs.indexOf(d[0])<0) e['doc_'+d[0]]='Required.'; });
  return e;
}
function snDocs(){ if(S.ui.sn_k==='end'){ var ty=ENDO[S.ui.sn_type]; return ty?ty.docs:[]; } if(S.ui.sn_k==='clm') return [['Claim intimation letter',1],['Photographs of the loss',1],['FIR or police report',S.ui.sn_cause==='Burglary or theft'?1:0],['Invoices for the damaged items',0]]; return []; }
SCREENS.svcnew=function(){
  /* [stated 24 Sep · TBD-52] the account's owner raises it — an RM, or a head of RM on her own accounts */
  var u=me(); if(!S.data.accounts.some(function(x){return x.own===u.id&&x.pols.length;})) return {sc:'Raise a ticket', html:empty('lock','For the account owner','Endorsements and claims are raised by whoever owns the account after handover. You own no account with a policy on it. Sales sees them on the account.','<button class="btn" data-back="1">'+ic('arrowleft')+'Back</button>')};
  var k=S.ui.sn_k||'', accts=S.data.accounts.filter(function(a){return a.pols.length&&a.own===u.id;}).sort(function(x,y){return x.n.localeCompare(y.n);}), a=by(S.data.accounts,S.ui.sn_acct||''), p=a?a.pols.filter(function(x){return x.id===S.ui.sn_pol;})[0]:null, e=snErr(), docs=(S.ui.sn_docs||'').split('|').filter(Boolean);
  var step=function(n,title,body){ return '<section class="card"><div class="cardh"><span class="t">'+n+' · '+esc(title)+'</span></div><div class="cardb">'+body+'</div></section>'; };
  var html='<div class="crumbs"><button data-go="tickets">Tickets</button>'+ic('chevright','ic14')+'<b>Raise a request</b></div><div class="h1">Raise a request</div><div class="sub">One ticket per change or per loss, on one policy. The desk verifies it, sets the category, and takes it to the insurer.</div>'+diamonds()+'<div class="gap12">'+
    step(1,'What kind', '<div class="fgrid">'+opt('data-uiset="sn_k" data-uv="end"',k==='end','Endorsement','A change to a policy in force — sum insured, location, name, bank details, cancellation')+opt('data-uiset="sn_k" data-uv="clm"',k==='clm','Claim','A loss under a policy — intimate it, appoint a surveyor, settle')+'</div>')+
    (k?step(2,'Which policy', '<div class="fgrid">'+field('Account','<select class="sel" data-uisel="sn_acct"><option value="">Choose an account</option>'+accts.map(function(x){return '<option value="'+x.id+'"'+(a&&a.id===x.id?' selected':'')+'>'+esc(x.n)+(x.own===u.id?'':' · owner '+esc(uname(x.own)))+'</option>';}).join('')+'</select>')+
        field('Policy',a?'<select class="sel" data-uisel="sn_pol"><option value="">Choose a policy</option>'+a.pols.map(function(x){ var ps=polState(x); return '<option value="'+x.id+'"'+(p&&p.id===x.id?' selected':'')+'>'+esc(x.id)+' · '+esc(x.p)+' · '+esc(ps.tx)+'</option>'; }).join('')+'</select>':'<select class="sel" disabled><option>Pick the account first</option></select>','',e.pol)+'</div>'+
        (p?'<div class="kvgrid mt8">'+kv('Insurer',esc(p.ins))+kv('Sum insured',esc(p.si))+kv('Period ends',esc(fmtD(p.exp))+' '+chip(polState(p).tx,polState(p).tone,false,true))+kv('Endorsements so far',String(p.endo||0))+'</div>':'')):'')+
    (k&&p&&!e.pol?step(3,k==='end'?'What needs to change':'The loss', k==='end'
        ? field('Endorsement type','<select class="sel" data-uisel="sn_type"><option value="">Choose…</option>'+Object.keys(ENDO).map(function(n){return '<option'+(S.ui.sn_type===n?' selected':'')+'>'+esc(n)+'</option>';}).join('')+'</select>')+
          (ENDO[S.ui.sn_type]?note(ENDO[S.ui.sn_type].cat?'violet':'neutral',ENDO[S.ui.sn_type].cat?ENDO[S.ui.sn_type].cat:'Category set at verification',ENDO[S.ui.sn_type].d,'info')+'<div class="fgrid">'+ENDO[S.ui.sn_type].f.map(function(f,i){ var key='sn_f'+i, v=S.ui[key]||''; var inner=f[1]==='sel'?'<select class="sel" data-uisel="'+key+'"><option value="">Choose…</option>'+f[3].map(function(o){return '<option'+(v===o?' selected':'')+'>'+esc(o)+'</option>';}).join('')+'</select>':(f[1]==='date'?'<input class="inp" type="date" id="'+key+'" data-ui="'+key+'" value="'+esc(v)+'">':'<input class="inp" id="'+key+'" data-ui="'+key+'" value="'+esc(v)+'" placeholder="'+esc(f[1]==='cur'?'₹':(f[1]==='pin'?'411001':''))+'">'); return field(f[0]+(f[2]?'':' — optional'),inner,'',v||S.ui.sn_touch?e['f'+i]:''); }).join('')+'</div>':'')
        : '<div class="fgrid">'+field('Cause of loss','<select class="sel" data-uisel="sn_cause"><option value="">Choose…</option>'+CAUSES.map(function(c){return '<option'+(S.ui.sn_cause===c?' selected':'')+'>'+esc(c)+'</option>';}).join('')+'</select>')+field('Date of loss','<input class="inp" type="date" id="sn_dol" data-ui="sn_dol" max="'+ymd(S.now)+'" value="'+esc(S.ui.sn_dol||'')+'">','',e.dol&&S.ui.sn_dol?e.dol:'')+'</div>'+
          '<div class="fgrid">'+field('Estimated loss','<input class="inp" id="sn_est" data-ui="sn_est" value="'+esc(S.ui.sn_est||'')+'" placeholder="₹6,20,000">','',S.ui.sn_est?e.est:'')+field('Intimated through','<select class="sel" data-uisel="sn_chan">'+['RM Interface','Email','BimaKendra','Phone'].map(function(c){return '<option'+((S.ui.sn_chan||'RM Interface')===c?' selected':'')+'>'+c+'</option>';}).join('')+'</select>')+'</div>'+
          field('What happened','<input class="inp" id="sn_desc" data-ui="sn_desc" value="'+esc(S.ui.sn_desc||'')+'" placeholder="Fire in the paint shop at the Chakan plant, contained in 40 minutes">')+
          (p&&(p.expired||p.exp<S.now)?note('amber','Expired policy','A claim can still be intimated if the loss happened inside the policy period. The date of loss decides it.'):'')):'')+
    (k&&p&&!e.pol&&(k==='clm'||ENDO[S.ui.sn_type])?step(4,'Documents', snDocs().length?'<div class="docs">'+snDocs().map(function(d){ var on=docs.indexOf(d[0])>=0; return '<label class="'+(on?'on':'')+'"><input type="checkbox" class="chk" data-sndoc="'+esc(d[0])+'"'+(on?' checked':'')+'>'+esc(d[0])+(d[1]?' <span class="meta">· required</span>':' <span class="meta">· optional</span>')+'</label>'; }).join('')+'</div><div class="meta mt8">Ticking stands in for the upload. Required documents block submission; the desk asks for the rest on the ticket.</div>':'<div class="meta">No document is needed for this type.</div>'):'')+
    (k&&p&&!e.pol?'<div class="flex wrap"><button class="btn primary lg" data-svcsubmit="1"'+(Object.keys(e).length?' disabled':'')+'>Submit to the desk</button><button class="btn ghost" data-go="tickets">Cancel</button>'+(Object.keys(e).length?'<span class="meta">'+Object.keys(e).length+' thing'+(Object.keys(e).length===1?'':'s')+' still needed: '+Object.keys(e).map(function(x){return x.indexOf('doc_')===0?x.slice(4):({k:'kind',acct:'account',pol:'policy',type:'type',cause:'cause',dol:'date of loss',est:'estimate',desc:'description'}[x]||(ENDO[S.ui.sn_type]&&x.indexOf('f')===0?ENDO[S.ui.sn_type].f[+x.slice(1)][0].toLowerCase():x));}).join(', ')+'</span>':'')+'</div>':'')+
    '</div>';
  return {sc:'Raise a request', html:html, cta:''};
};
HANDLERS.push(function(t){
  var x=t.closest('[data-sndoc]'); if(x){ var docs=(S.ui.sn_docs||'').split('|').filter(Boolean), i=docs.indexOf(x.dataset.sndoc); if(i>=0) docs.splice(i,1); else docs.push(x.dataset.sndoc); S.ui.sn_docs=docs.join('|'); paint(); return true; }
  x=t.closest('[data-svcsubmit]'); if(!x) return false; if(x.disabled) return true;
  var e=snErr(); if(Object.keys(e).length){ S.ui.sn_touch=1; paint(); toast('Not yet','Fix what is marked and try again.',{red:1}); return true; }
  var k=S.ui.sn_k, a=by(S.data.accounts,S.ui.sn_acct), p=a.pols.filter(function(x){return x.id===S.ui.sn_pol;})[0], tk;
  var ok=write(function(){
    var docs=(S.ui.sn_docs||'').split('|').filter(Boolean), missing=snDocs().filter(function(d){return docs.indexOf(d[0])<0;}).map(function(d){return {d:d[0],age:'0 days',got:0,opt:1};});
    if(k==='end'){ var ty=ENDO[S.ui.sn_type]; tk={id:'END-RM-'+String(S.data.seq.svc++).padStart(6,'0'),k:'end',acct:a.id,pol:p.id,prod:p.p,ins:p.ins,sub:S.ui.sn_type,cat:ty.cat,raised:S.now,chan:'RM Interface',sm:'',phase:0,stage:'Submitted',wait:'Desk',need:0,out:[],fields:ty.f.map(function(f,i){return [f[0],S.ui['sn_f'+i]||'—'];}),docs:docs,thread:[{d:'sys',w:'System',r:'',at:S.now,b:'Submitted by '+uname(S.user)+'. Awaiting verification by the desk.'}]}; p.endo=(p.endo||0)+1; }
    else { tk={id:'CLM-'+String(S.data.seq.clm++).padStart(4,'0'),k:'clm',acct:a.id,pol:p.id,prod:p.p,ins:p.ins,sub:S.ui.sn_cause,raised:S.now,chan:S.ui.sn_chan||'RM Interface',sm:'',stage:'Intimated',client:'Intimated',wait:'Desk',need:0,contest:0,srv:null,dol:S.ui.sn_dol,est:S.ui.sn_est,desc:S.ui.sn_desc,out:[],docs:docs,thread:[{d:'sys',w:'System',r:'',at:S.now,b:'Claim intimated by '+uname(S.user)+' · loss on '+fmtD(new Date(S.ui.sn_dol+'T12:00:00').getTime())+' · estimate '+S.ui.sn_est}]}; }
    S.data.svc.unshift(tk);
  },'the ticket');
  if(!ok) return true;
  Object.keys(S.ui).forEach(function(k2){ if(k2.indexOf('sn_')===0) delete S.ui[k2]; });
  go('svctix',{id:tk.id}); toast((k==='end'?'Endorsement':'Claim')+' raised — '+tk.id,'With the desk. You will be asked here if anything is missing.'); return true;
});

/* ---------- ticket detail ---------- */
SCREENS.svctix=function(){
  var t=svcById(S.route.id); if(!t) return SCREENS.notfound();
  var a=acctOf(t.acct), p=polOf(t), u=me(), nd=svcNeed(t), cl=svcClosed(t), can=svcCanAct(t), ph=t.k==='end'?PHASES:CPHASES, pi=svcPhaseIdx(t);
  var q=t.query&&t.query.open?t.query:null, qdue=q?q.at+(q.sla||24)*3600000:0;
  var canWithdraw=can&&(t.k==='end'?(t.phase||0)<2:t.stage==='Intimated');
  var html='<div class="crumbs"><button data-go="tickets">Tickets</button>'+ic('chevright','ic14')+'<b>'+esc(t.id)+'</b></div>'+
    '<div class="hdrow"><div><div class="h1">'+esc(t.sub)+'</div><div class="metaline"><span class="b">'+esc(a?a.n:t.acct)+'</span><span class="sep">·</span><span>'+esc(t.id)+'</span><span class="sep">·</span>'+chip(t.k==='clm'?'Claim':'Endorsement'+(t.cat?' · '+t.cat:''),'neutral',false,true)+chip(t.stage,cl?'green':(nd?'amber':'violet'),true,true)+chip('Waiting on '+(nd?'you':t.wait),nd?'amber':(t.wait==='Insurer'?'blue':'neutral'),false,true)+'</div></div><span class="sp"></span>'+
      '<div class="acts">'+(can?'<button class="btn sm" data-flow="svcAsk" data-svc="'+t.id+'">Ask the desk</button>':'')+(can?'<button class="btn sm ghost" data-flow="svcWithdraw" data-svc="'+t.id+'"'+(canWithdraw?'':' disabled title="Past the point of withdrawal"')+'>Withdraw</button>':'')+'</div></div>'+
    (!can&&!cl?'<div class="banner neutral mt12">'+ic('eye','ic14')+'<span>Read-only. This ticket is worked by '+esc(uname(a?a.own:''))+', the account’s RM'+(u.role==='rm'||u.role==='rmhead'?'':' — sales sees it for context')+'.</span></div>':'')+
    (cl?'<div class="banner green mt12">'+ic('circlecheck','ic14')+'<span><b>'+esc(t.stage)+'</b>'+(t.refund?' · refund '+esc(t.refund.amt)+' credited, UTR '+esc(t.refund.utr):'')+'. Nothing more to do on this ticket.</span></div>':'')+
    diamonds()+
    '<div class="two"><div class="rail">'+
      '<div class="clock '+(cl?'green':(nd?'red':'blue'))+'"><div class="top"><span>Ticket clock</span><span class="own">'+esc(t.sm||'Unassigned')+'</span></div><div class="hl">'+(cl?'Closed':plural(daysBetween(t.raised,S.now),'day')+' open')+'</div><div class="bar"><i style="width:'+Math.min(100,Math.round((pi+1)/ph.length*100))+'%"></i></div><div class="l1">'+esc(t.stage)+'<span> · '+esc(t.chan)+'</span></div><div class="l2">'+ic('clock','ic14')+'Raised '+esc(fmt(t.raised))+'</div></div>'+
      (q?'<div class="na red"><div class="k">Needs your reply</div><div class="i">'+esc(q.who)+' asked a question</div><div class="w">Due '+esc(fmt(qdue))+(S.now>qdue?' · <span class="red">overdue</span>':'')+'. The ticket does not move until it is answered.</div>'+(can?'<div class="acts"><button class="btn primary lg full" data-flow="svcReply" data-svc="'+t.id+'">Reply to the desk</button></div>':'')+'</div>'
        : (nd?'<div class="na amber"><div class="k">Needs you</div><div class="i">The desk is waiting for documents from the client</div><div class="w">Mark each one received as it comes in.</div></div>'
        : (cl?'<div class="na green"><div class="k">Done</div><div class="i">'+esc(t.stage)+'</div></div>':'<div class="na blue"><div class="k">Waiting on '+esc(t.wait)+'</div><div class="i">'+esc(t.stage)+'</div><div class="w">Nothing is needed from you. Ask the desk if the client is chasing.</div></div>')))+
      (can?simblock('Simulate the desk','What the servicing desk or the insurer does off this screen.',(q?'':simbtn('Desk raises a query','data-svcsim="query" data-svc="'+t.id+'"'))+(t.k==='end'&&(t.phase||0)<4?simbtn('Desk moves it on','data-svcsim="next" data-svc="'+t.id+'"'):'')+(t.k==='clm'&&t.stage==='Intimated'?simbtn('Surveyor appointed','data-svcsim="srv" data-svc="'+t.id+'"'):'')+(t.k==='clm'&&(t.stage==='Surveyor appointed'||t.stage==='Under assessment')?simbtn('Insurer approves','data-svcsim="approve" data-svc="'+t.id+'"')+simbtn('Insurer repudiates','data-svcsim="repud" data-svc="'+t.id+'"'):'')+(t.k==='clm'&&t.stage==='Repudiation contested with the insurer'?simbtn('Insurer reverses, approves','data-svcsim="approve" data-svc="'+t.id+'"'):'')+(t.k==='clm'&&t.stage==='Approved'?simbtn('Insurer settles','data-svcsim="settle" data-svc="'+t.id+'"'):'')):'')+
    '</div><div class="pane"><div class="pb">'+
      '<div class="phhd"><div class="t">Where it is</div><div class="a">'+(pi>=0?'phase '+(pi+1)+' of '+ph.length:'withdrawn')+'</div></div>'+
      '<div class="phases mt12" style="grid-template-columns:repeat('+ph.length+',minmax(0,1fr))">'+ph.map(function(n,i){ return '<div class="ph'+(i<pi?' done':(i===pi?' now':''))+'"><div class="b"></div><div class="t">'+esc(n)+'</div></div>'; }).join('')+'</div>'+
      (t.k==='clm'&&t.contest?'<div class="wall mt12"><b>Two labels, on purpose.</b> Internally this is <b>'+esc(t.stage)+'</b>. The client sees <b>'+esc(svcClientLabel(t))+'</b> on BimaKendra — a repudiation under contest is not shown to the client until the contest is decided.</div>':(t.k==='clm'&&t.client&&t.client!==t.stage?'<div class="meta mt8">Client sees: '+esc(t.client)+'</div>':''))+
      diamonds(true)+'<div class="kvgrid">'+kv('Policy','<span class="mono">'+esc(t.pol)+'</span><div class="meta">'+esc(t.prod)+' · '+esc(t.ins)+(p?' · ends '+esc(fmtD(p.exp)):'')+'</div>')+kv('Account','<button class="link" data-go="acct" data-id="'+t.acct+'">'+esc(a?a.n:t.acct)+'</button>')+kv('Servicing manager',esc(t.sm||'Not yet assigned'))+kv('Raised through',esc(t.chan)+' · '+esc(fmtD(t.raised)))+(t.dol?kv('Date of loss',esc(fmtD(new Date(t.dol+'T12:00:00').getTime()))):'')+(t.est?kv('Estimated loss',esc(t.est)):'')+'</div>'+
      (t.fields?diamonds(true)+'<div class="h3">What was asked</div><div class="kvgrid mt12">'+t.fields.map(function(f){return kv(f[0],esc(f[1]));}).join('')+'</div>':'')+(t.desc?diamonds(true)+'<div class="h3">What happened</div><div class="mt8" style="font-size:var(--fs-base);color:var(--ink2)">'+esc(t.desc)+'</div>':'')+
      (t.srv?diamonds(true)+'<div class="h3">Surveyor</div><div class="kvgrid mt12">'+kv('Name',esc(t.srv.n))+kv('Mobile',esc(t.srv.m))+kv('Visit',esc(t.srv.d))+'</div>':'')+
      (t.refund?diamonds(true)+'<div class="h3">Refund</div><div class="kvgrid mt12">'+kv('Amount','<b>'+esc(t.refund.amt)+'</b>')+kv('Insurer reference','<span class="mono">'+esc(t.refund.ref)+'</span>')+kv('UTR','<span class="mono">'+esc(t.refund.utr)+'</span>')+'</div>':'')+
      (t.out&&t.out.length?diamonds(true)+'<div class="flex"><div class="h3">Documents the desk needs</div><span class="sp"></span>'+chip(t.out.filter(function(d){return !d.got;}).length+' outstanding',t.out.some(function(d){return !d.got;})?'amber':'green',false,true)+'</div><div class="rowlist mt8" style="border:1px solid var(--border);border-radius:12px">'+t.out.map(function(d,i){ return '<div><div class="bd"><b'+(d.got?' style="text-decoration:line-through;color:var(--ink3)"':'')+'>'+esc(d.d)+'</b><div class="m2">'+(d.got?'Received':'Asked '+esc(d.age)+' ago')+'</div></div><div class="rt">'+(can&&!d.got?'<button class="btn sm" data-svcdoc="'+i+'" data-svc="'+t.id+'">Mark received</button>':(d.got?chip('In','green',false,true):''))+'</div></div>'; }).join('')+'</div>':'')+
      diamonds(true)+'<div class="flex"><div class="h3">Thread</div><span class="sp"></span>'+(can?'<button class="btn sm" data-flow="svcAsk" data-svc="'+t.id+'">Ask the desk</button>':'')+'</div>'+
      '<div class="msgs mt12">'+(q?'<div class="msg in"><div class="w"><b>'+esc(q.who)+'</b> · Servicing manager · '+esc(fmt(q.at))+' · '+chip('Query · open','amber',true,true)+'</div>'+esc(q.q)+'</div>':'')+t.thread.slice().sort(function(x,y){return y.at-x.at;}).map(function(m){ return '<div class="msg '+m.d+'">'+(m.d==='sys'?esc(m.b)+' · '+esc(fmt(m.at)):'<div class="w"><b>'+esc(m.w)+'</b>'+(m.r?' · '+esc(m.r):'')+' · '+esc(fmt(m.at))+'</div>'+esc(m.b))+'</div>'; }).join('')+'</div>'+
    '</div></div></div>';
  return {sc:'Service ticket', ctx:t.id, html:html, cta: (isRole('rm')||isRole('rmhead'))?'<button class="btn primary sm" data-go="svcnew">'+ic('plus')+'Raise request</button>':''};
};
HANDLERS.push(function(t){
  var x=t.closest('[data-flow="svcAsk"],[data-flow="svcReply"],[data-flow="svcWithdraw"]'); if(x){ if(x.disabled) return true; openFlow(x.dataset.flow,{svc:x.dataset.svc}); return true; }
  x=t.closest('[data-svcdoc]'); if(x){ var tk=svcById(x.dataset.svc); if(!tk) return true; var d=tk.out[+x.dataset.svcdoc]; var ok=write(function(){ d.got=1; tk.thread.push({d:'sys',w:'System',r:'',at:S.now,b:'Received: '+d.d+' · marked by '+uname(S.user)}); if(!tk.out.some(function(z){return !z.got;})){ tk.wait='Desk'; tk.thread.push({d:'sys',w:'System',r:'',at:S.now,b:'All documents in. Back with the desk.'}); } },'the document'); if(ok){ paint(); toast('Marked received',tk.out.some(function(z){return !z.got;})?'':'Everything the desk asked for is in — the ticket is back with them.'); } return true; }
  x=t.closest('[data-svcsim]'); if(x){ var tk2=svcById(x.dataset.svc); if(!tk2) return true; svcSim(x.dataset.svcsim,tk2); return true; }
  return false;
});
function svcSim(k,t){
  var msg='';
  var ok=write(function(){
    if(k==='query'){ t.query={q:t.k==='end'?'The effective date on the request is before the last endorsement. Please confirm the client wants it backdated, or give a new date.':'The surveyor needs access to the site on a working day this week. Which day suits the client?',who:t.sm||'Farhan Qureshi',at:S.now,open:1,sla:24}; t.sm=t.sm||'Farhan Qureshi'; t.wait='You'; msg='Query raised — it is waiting on you'; }
    if(k==='next'){ t.phase=Math.min(4,(t.phase||0)+1); t.stage=PHASES[t.phase]; t.sm=t.sm||'Farhan Qureshi'; t.wait=t.phase===2?'Insurer':(t.phase===3?'Client':(t.phase===4?'—':'Desk')); t.thread.push({d:'sys',w:'System',r:'',at:S.now,b:t.phase===1?'Ticket accepted and assigned to '+t.sm+'.':(t.phase===2?'Submitted to insurer.':(t.phase===3?'Endorsement premium computed. Payment link sent to the client on BimaKendra.':'Completed. Endorsement schedule issued.'))}); msg='Now '+t.stage; }
    if(k==='srv'){ t.stage='Surveyor appointed'; t.client='Surveyor assigned'; t.sm=t.sm||'Deepa Kulkarni'; t.srv={n:'R. Krishnan',m:'+91 98400 11207',d:fmtD(addWork(S.now,3*540))}; t.wait='Client'; t.out=t.out.length?t.out:[{d:'Photographs of the damaged items',age:'0 days',got:0},{d:'Repair estimate from the vendor',age:'0 days',got:0}]; t.thread.push({d:'sys',w:'System',r:'',at:S.now,b:'Surveyor appointed — R. Krishnan. Visit '+t.srv.d+'.'}); msg='Surveyor appointed · documents requested from the client'; }
    if(k==='approve'){ t.stage='Approved'; t.client='Approved'; t.contest=0; t.wait='Insurer'; t.thread.push({d:'sys',w:'System',r:'',at:S.now,b:'Insurer approved the claim'+(t.est?' · assessed at '+t.est:'')+'.'}); msg='Approved — settlement follows'; }
    if(k==='repud'){ t.stage='Repudiation contested with the insurer'; t.client='Under assessment'; t.contest=1; t.wait='Insurer'; t.thread.push({d:'in',w:t.sm||'Deepa Kulkarni',r:'Servicing manager',at:S.now,b:'Insurer has repudiated citing a policy condition. We are contesting. The client label stays at Under assessment.'}); msg='Repudiated — under contest. The client still sees Under assessment.'; }
    if(k==='settle'){ t.stage='Settled'; t.client='Settled'; t.wait='—'; t.thread.push({d:'sys',w:'System',r:'',at:S.now,b:'Settled. '+(t.est||'The assessed amount')+' released to the registered account.'}); msg='Settled'; }
  },'the simulated event');
  if(!ok) return; paint(); toast('Desk update',msg);
}
FLOWS.svcReply={t:'Reply to the desk', sub:function(){ var t=svcById(S.sel.svc); return t&&t.query?t.query.who+' is waiting on this. The SLA clock on the query stops when you send.':''; },
  body:function(){ var t=svcById(S.sel.svc); return note('amber',t.query.who,t.query.q,'mail')+field('Your reply',input('x',S.sel.x,'What the client said, or the document you have attached'))+field('Attach a document — optional',select('doc',S.sel.doc||'',[['','Nothing attached'],'Clearer scan of the cancelled cheque','Bank letter on letterhead','Client email confirming the date','Site access confirmation']))+note('blue','','The reply goes on the ticket as you. The client is not copied — you relay.'); },
  can:function(){ return !!(S.sel.x||'').trim(); }, ok:'Send reply',
  run:function(){ var t=svcById(S.sel.svc); var ok=write(function(){ t.thread.push({d:'in',w:t.query.who,r:'Servicing manager',at:t.query.at,b:t.query.q}); t.thread.push({d:'out',w:uname(S.user),r:'reply to the desk',at:S.now,b:S.sel.x.trim()+(S.sel.doc?' · attached: '+S.sel.doc:'')}); t.query.open=0; t.wait='Desk'; },'the reply'); if(!ok) return 'fail'; toast('Reply sent','Back with the desk. Nothing is waiting on you here.'); }};
FLOWS.svcAsk={t:'Ask the desk', sub:'A question on the ticket. It does not change where the ticket is.',
  body:function(){ return field('Your question',input('x',S.sel.x,'Is the surveyor visit blocked on these documents?'))+note('neutral','','Answered on the thread by the servicing manager, usually inside a working day.','info'); },
  can:function(){ return !!(S.sel.x||'').trim(); }, ok:'Send',
  run:function(){ var t=svcById(S.sel.svc); var ok=write(function(){ t.thread.push({d:'out',w:uname(S.user),r:'your question to the desk',at:S.now,b:S.sel.x.trim()}); },'the question'); if(!ok) return 'fail'; toast('Sent to the desk',''); }};
FLOWS.svcWithdraw={t:'Withdraw this ticket', sub:'Only before the desk has taken it to the insurer. After that it is cancelled by the insurer, not withdrawn by us.',
  body:function(){ return field('Reason',select('rs',S.sel.rs||'',[['','Choose…'],'Client changed their mind','Raised in error','Duplicate of another ticket','Client will renew instead']))+note('red','Cannot be undone','The ticket closes as Withdrawn and stays on the record.','alert'); },
  can:function(){ return !!S.sel.rs; }, ok:'Withdraw',
  run:function(){ var t=svcById(S.sel.svc); var ok=write(function(){ t.stage='Withdrawn'; t.client='Withdrawn'; t.wait='—'; if(t.query) t.query.open=0; t.thread.push({d:'sys',w:'System',r:'',at:S.now,b:'Withdrawn by '+uname(S.user)+' · '+S.sel.rs}); },'the withdrawal'); if(!ok) return 'fail'; toast('Withdrawn',''); }};
